name: 'Parse Docker Scout Output'
description: "A GitHub Action to parse Docker Scout's Output"
author: 'Renzo Franceschini'

inputs:
  TARGET_REPO:
    description: 'Target GitHub Repo to upload images to'
    required: true
  TARGET_BRANCH:
    description: "Target Repo's Branch to upload images to"
    required: true
  TARGET_FOLDER:
    description: 'Folder name in the repository to upload images to'
    required: true
  RECOMMENDATIONS:
    description: 'Docker Scout recommendations HTML output'
    required: true
  CVES_OUTPUT:
    description: 'Docker Scout CVEs HTML output'
    required: true
  SBOM_OUTPUT:
    description: 'Docker Scout SBOM JSON output'
    required: true
  IMAGE_DETAILS:
    description: 'Docker image details JSON'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'book-open'
  color: 'black'